namespace HMS.Infrastructure.Persistence.Entities.Security;
internal sealed class AppUser { public Guid UserId { get; set; } public string Username { get; set; }=null!; public string? Email { get; set; } public string? Phone {get;set;} public string? PasswordHash {get;set;} public string? PasswordSalt {get;set;} public bool IsActive {get;set;} public bool IsDeleted {get;set;} public int FailedLoginCount {get;set;} public DateTime? LockedUntil {get;set;} public DateTime? LastLoginAt {get;set;} public DateTime CreatedAt {get;set;} }
internal sealed class RefreshToken { public Guid RefreshTokenId {get;set;} public Guid UserId {get;set;} public Guid JwtId {get;set;} public byte[] TokenHash {get;set;}=null!; public DateTime IssuedAt {get;set;} public DateTime ExpiresAt {get;set;} public DateTime? RevokedAt {get;set;} public DateTime? UsedAt {get;set;} public Guid? ReplacedByTokenId {get;set;} }
internal sealed class AccessToken { public Guid AccessTokenId {get;set;} public Guid UserId {get;set;} public Guid JwtId {get;set;} public byte[] TokenHash {get;set;}=null!; public DateTime IssuedAt {get;set;} public DateTime ExpiresAt {get;set;} public DateTime? RevokedAt {get;set;} public string? DeviceIP {get;set;} public string? UserAgent {get;set;} }
internal sealed class LoginHistory { public long LoginHistoryId {get;set;} public Guid? UserId {get;set;} public DateTime LoginAt {get;set;} public bool IsSuccessful {get;set;} public string? FailureReason {get;set;} public string? IPAddress {get;set;} public string? UserAgent {get;set;} public DateTime CreatedAt {get;set;} public bool IsDeleted {get;set;} }
internal sealed class UserRole { public Guid UserId {get;set;} public long RoleId {get;set;} }
internal sealed class Role { public long RoleId {get;set;} public string RoleCode {get;set;}=null!; public bool IsDeleted {get;set;} }
internal sealed class RolePermission { public long RoleId {get;set;} public long PermissionId {get;set;} }
internal sealed class Permission { public long PermissionId {get;set;} public string PermissionCode {get;set;}=null!; public bool IsDeleted {get;set;} }
